### ISSUE TITLE
Create the CU Hack Night website

### ISSUE THREAD

**Issue by sanfordhess** [CUHackNight/breakout-groups#1]
We need to create out own website to create a web presence and share the word!  Working as a group, we'll create this website at our meeting, and probably revamp it through many iterations in the weeks ahead.

**Comment by julianchin** [comment]
February 28, 2017

**Social media** is for outreach (dates, meeting dates--update in one place); 
* We set up a Facebook page: https://www.facebook.com/CU-Hack-Night-1655253491437866/
* Gmail account: cuhacknight@gmail.com
* Twitter: @cuhacknight

**Website** is for specific information: 
* location, meeting dates, and groups, and info about Hack Night histories
* Contact info
* Job postings
* Current projects
* Recruiting is primary; what projects are secondary

*Third Side is willing to host, WordPress as option, Square space has domain name*

**Target groups**:
* Communication
* Designers
* Educators (formal or informal)
* Techies
* Community members

People
* Thinking together; imagining the future to solve challenges in the community, By solving challenges in the community
* Bring your problem and people will swarm to it
* Everyone has something to offer
* Giving back

Define the groups: wide age range, curious people, and people who want to give back
Residents, community members 

**Mission**: 
* Using technology and data to solve problems; find solutions; bring a better community

**Illustration**:
* Imagery to illustrate “about” which is different from logo
* Narrate our story
* Ideas:
  * Round table, light bulb, linking arms or hands, candle, tools to hack--axes, hatchets, screwdrivers, ones and zeros, 
  * Xy axis, navigation (direction, orientation, landscape) how people fit into a map; where do you want to go? 
  * Eating together, food
  * Indication of Champaign-Urbana (CU): corn, street separation, not oppositional, bringing it closer together, expands who is our community; university is part of the community and they can also be involved, even though they may be transient
  * People float in and out depending on subject and time commitments
  * Agriculturally enhanced
  * Corn plant with tassel and ones and zeros
  * Word banners connect to corn plant (gets toward illustration)
  * Text creates challenge; logo should be recognizable without text

**Taglines**:
* Fun, Ideation
* CU Hack Nights...Finding community solutions
* We know what you’re thinking...but that is not what we are.
* How do you hack into the institution? How do you hack into racism? How do you hack into community? And what does that mean? 
* Social gathering--that is a hack because we are not necessarily meant to be in the room together
* How do we define technology? 
* Reimagining community

**Comment by shrnirish** [comment]
![cuhn logo ideas](https://cloud.githubusercontent.com/assets/25937154/23926194/c9eea002-08e0-11e7-8df3-70f1e8d9678b.jpg)
from Stacey Robinson

**Comment by shrnirish** [comment]
From Kyle Weise 
![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/25937154/23927087/d465cae2-08e5-11e7-9b60-b0fef98f3dfb.jpg)

**Comment by shrnirish** [comment]
I found my notes from the March 7 meeting! We discussed having a google calendar plug-in on the website. Other tabs mentioned included About, Projects, Sponsors, and Contact Us. There was discussion about having a blog feed on the landing page that would describe current activities. On a sidebar there could be links to Facebook, Twitter, and the newsletter. I (Sharon) will not be at the March 21 meeting.

**Comment by shrnirish** [comment]
Tabs: Contact (with Twitter, FB, gmail, and Slack
Sponsors: homepage? Pixo, Volo, Pavlov, Parkland, Ground Zero at Parkland, US Ignite
About: CU Hack Nights...Finding solutions to community challenges. Hack Nights began as a community group in January 2017. We meet on Tuesdays, from 6-8pm, at Parkland College, Room X-125, in Wing X. Generally about 20 people attend, but we would welcome more! Our meetings usually have food--pizza and fruit, with drinks from nearby vending machines.
Projects (link to github): In Spring of 2017, we are discussing topics ranging from bee pollination, to mass transit, to public health. We locate publicly available data and see if we can help address challenges in our communities. Most especially, we have fun getting together to create new solutions with new and old friends.

**Comment by shrnirish** [comment]
On April 11, we decided on tab titles and general organization of information. Sponsor logos will go on home page. Tab titles: SHARE AN IDEA (leads to a webform with Qs); DISCOVER (who we are); INTERACT (sign up for newsletter, SignUpGenius, link to github)
for the webform, suggested questions (that would go to email):
SHARE AN IDEA
Name
Email
Do you want to share an idea? Please describe.
Do you need help to realize your idea? Be as specific as you can.
Do you have skills to offer?

**Comment by sanfordhess** [comment]
Marking this one... done!
